//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWind.Sales.Frontend.Views.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CreateOrderMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateOrderMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NorthWind.Sales.Frontend.Views.Resources.CreateOrderMessages", typeof(CreateOrderMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CustomerIdLabel {
            get {
                return ResourceManager.GetString("CustomerIdLabel", resourceCulture);
            }
        }
        
        internal static string ShipAddressLabel {
            get {
                return ResourceManager.GetString("ShipAddressLabel", resourceCulture);
            }
        }
        
        internal static string ShipCityLabel {
            get {
                return ResourceManager.GetString("ShipCityLabel", resourceCulture);
            }
        }
        
        internal static string ShipCountryLabel {
            get {
                return ResourceManager.GetString("ShipCountryLabel", resourceCulture);
            }
        }
        
        internal static string ShipPostalCodeLabel {
            get {
                return ResourceManager.GetString("ShipPostalCodeLabel", resourceCulture);
            }
        }
        
        internal static string ProductIdLabel {
            get {
                return ResourceManager.GetString("ProductIdLabel", resourceCulture);
            }
        }
        
        internal static string UnitPriceLabel {
            get {
                return ResourceManager.GetString("UnitPriceLabel", resourceCulture);
            }
        }
        
        internal static string QuantityLabel {
            get {
                return ResourceManager.GetString("QuantityLabel", resourceCulture);
            }
        }
        
        internal static string AddProductButtonText {
            get {
                return ResourceManager.GetString("AddProductButtonText", resourceCulture);
            }
        }
        
        internal static string SendButtonText {
            get {
                return ResourceManager.GetString("SendButtonText", resourceCulture);
            }
        }
        
        internal static string CreateOrderTemplate {
            get {
                return ResourceManager.GetString("CreateOrderTemplate", resourceCulture);
            }
        }
        
        internal static string CreateOrderMenuItemTitle {
            get {
                return ResourceManager.GetString("CreateOrderMenuItemTitle", resourceCulture);
            }
        }
        
        internal static string CreateOrderPageTitle {
            get {
                return ResourceManager.GetString("CreateOrderPageTitle", resourceCulture);
            }
        }
    }
}
