//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWind.Exceptions.Entities.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessage {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessage() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NorthWind.Exceptions.Entities.Resources.ExceptionMessage", typeof(ExceptionMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ValidationExceptionTitle {
            get {
                return ResourceManager.GetString("ValidationExceptionTitle", resourceCulture);
            }
        }
        
        internal static string ValidationExceptionDetail {
            get {
                return ResourceManager.GetString("ValidationExceptionDetail", resourceCulture);
            }
        }
        
        internal static string UpdateExceptionTitle {
            get {
                return ResourceManager.GetString("UpdateExceptionTitle", resourceCulture);
            }
        }
        
        internal static string UpdateExceptionDetail {
            get {
                return ResourceManager.GetString("UpdateExceptionDetail", resourceCulture);
            }
        }
        
        internal static string UnhandledExceptionTitle {
            get {
                return ResourceManager.GetString("UnhandledExceptionTitle", resourceCulture);
            }
        }
        
        internal static string UnhandledExceptionDetail {
            get {
                return ResourceManager.GetString("UnhandledExceptionDetail", resourceCulture);
            }
        }
        
        internal static string UnauthorizedAccessExceptionDetail {
            get {
                return ResourceManager.GetString("UnauthorizedAccessExceptionDetail", resourceCulture);
            }
        }
        
        internal static string UnauthorizedAccessExceptionTitle {
            get {
                return ResourceManager.GetString("UnauthorizedAccessExceptionTitle", resourceCulture);
            }
        }
    }
}
